# Main application Makefile for Dreammp3
#
# (C) COPYRIGHT 2002 Ben(jamin) Gerard
#
# $Id: Makefile,v 1.5 2003-02-12 12:31:56 ben Exp $

LIBRARY=yes
OPTIMIZE = $(OPTIMIZE_FOR_SPEED)

TOPDIR:=$(dir $(shell pwd))

KOS_LOCAL_INCS := -iquote ../../include -iquote .. -iquote .

#KOS_LOCAL_CFLAGS += -DDREAMMP3_HOME="\"$(TOPDIR)\""

#include config

include ../../Makefile.inc
# DO NOT DELETE
